import { TTSManager } from "../lib/voice/tts_engine.js";
const $ = (id) => document.getElementById(id);
const defaults = { provider: "ollama", endpoint: "http://localhost:11434", model: "qwen2.5:3b", apiKey: "", maxContextTokens: 6000, whisperEndpoint: "", ttsEngine: "webspeech", voice: "", rate: 1, pitch: 1 };
const tts = new TTSManager();
let settings = { ...defaults };
function say(text, error = false) { $("status").textContent = text; $("status").style.color = error ? "#b91c1c" : "#166534"; }
function setModelOptions(models, selected) { $("model").replaceChildren(...models.filter(Boolean).map((id) => new Option(id, id, false, id === selected))); if (!models.includes(selected)) $("model").add(new Option(selected || "Enter a model after fetching", selected || "")); }
async function refreshVoices() { await tts.setEngine($("tts-engine").value); const voices = await tts.activeEngine.getVoices(); const selected = voices.some((voice) => voice.id === settings.voice) ? settings.voice : voices[0]?.id || ""; $("voice").replaceChildren(...voices.map((voice) => new Option(voice.name, voice.id, false, voice.id === selected))); if (!voices.length) say("No system voices were reported by the browser.", true); }
function endpointFor(provider) { return provider === "ollama" ? "http://localhost:11434" : provider === "lmstudio" ? "http://127.0.0.1:1234/v1" : provider === "openai" ? "https://api.openai.com/v1" : "https://api.anthropic.com/v1"; }
async function load() { settings = { ...defaults, ...(await browser.storage.local.get(defaults)) }; for (const id of ["provider","endpoint","api-key","context-tokens","whisper-endpoint","tts-engine","rate","pitch"]) $(id).value = settings[{ provider:"provider", endpoint:"endpoint", "api-key":"apiKey", "context-tokens":"maxContextTokens", "whisper-endpoint":"whisperEndpoint", "tts-engine":"ttsEngine", rate:"rate", pitch:"pitch" }[id]]; setModelOptions([settings.model], settings.model); $("rate-value").value = settings.rate; $("pitch-value").value = settings.pitch; await refreshVoices(); }
$("provider").addEventListener("change", () => { $("endpoint").value = endpointFor($("provider").value); });
$("tts-engine").addEventListener("change", () => refreshVoices().catch((error) => say(error.message, true)));
for (const id of ["rate", "pitch"]) $(id).addEventListener("input", () => { $(`${id}-value`).value = $(id).value; });
$("fetch-models").addEventListener("click", async () => { try { const endpoint = $("endpoint").value.replace(/\/$/, ""); const ollama = $("provider").value === "ollama"; const response = await fetch(`${endpoint}${ollama ? "/api/tags" : "/models"}`, { headers: $("api-key").value ? { Authorization: `Bearer ${$("api-key").value}` } : {} }); if (!response.ok) throw new Error(`Model discovery failed (${response.status})`); const data = await response.json(); const models = ollama ? (data.models || []).map((m) => m.name) : (data.data || []).map((m) => m.id); setModelOptions(models, models[0]); say(`Found ${models.length} model(s).`); } catch (error) { say(error.message, true); } });
$("test-voice").addEventListener("click", async () => { try { await tts.setEngine($("tts-engine").value); tts.setVoice($("voice").value); await tts.activeEngine.synthesize("Hi, I am Eevie. Voice replies are ready.", { voice: $("voice").value, rate: Number($("rate").value), pitch: Number($("pitch").value) }); say("Voice test played."); } catch (error) { say(`Voice test failed: ${error.message}`, true); } });
$("save").addEventListener("click", async () => { const next = { provider: $("provider").value, endpoint: $("endpoint").value.replace(/\/$/, ""), model: $("model").value, apiKey: $("api-key").value, maxContextTokens: Number($("context-tokens").value), whisperEndpoint: $("whisper-endpoint").value.replace(/\/$/, ""), ttsEngine: $("tts-engine").value, voice: $("voice").value, rate: Number($("rate").value), pitch: Number($("pitch").value) }; await browser.storage.local.set(next); settings = next; say("Saved locally."); });
load().catch((error) => say(error.message, true));
